/* Analysis export + sharing: Markdown plan, shareable URL hash, clipboard. */

import type { Analysis } from "../types";

const SHARE_PREFIX = "#a=";

const b64encode = (s: string) => btoa(unescape(encodeURIComponent(s)));
const b64decode = (s: string) => decodeURIComponent(escape(atob(s)));

/** Encodes only the analysis (never the resume) into a link. */
export function buildShareUrl(a: Analysis): string | null {
  try {
    return window.location.origin + window.location.pathname + SHARE_PREFIX + b64encode(JSON.stringify(a));
  } catch {
    return null;
  }
}

export function readSharedAnalysis(hash: string): Analysis | null {
  if (!hash || hash.indexOf(SHARE_PREFIX) !== 0) return null;
  try {
    const a = JSON.parse(b64decode(hash.slice(SHARE_PREFIX.length)));
    return a && a.roleSummary ? a : null;
  } catch {
    return null;
  }
}

export async function copyText(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    /* fall through */
  }
  const ta = document.createElement("textarea");
  ta.value = text;
  ta.style.position = "fixed";
  ta.style.left = "-9999px";
  document.body.appendChild(ta);
  ta.select();
  let ok = false;
  try {
    ok = document.execCommand("copy");
  } catch {
    ok = false;
  }
  ta.remove();
  return ok;
}

export function downloadText(filename: string, text: string, type = "text/markdown;charset=utf-8"): void {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    URL.revokeObjectURL(url);
    a.remove();
  }, 0);
}

export function planFilename(a: Analysis): string {
  const slug =
    (a.seniority || a.roleSummary || "offerready")
      .toString()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "offerready";
  return "offerready-plan-" + slug + ".md";
}

export function toMarkdown(a: Analysis): string {
  const L: string[] = [];
  const clean = (s: unknown) => String(s == null ? "" : s).replace(/\s+/g, " ").trim();
  L.push("# OfferReady — Preparation Plan");
  if (a.seniority) L.push("", "**Seniority:** " + clean(a.seniority));
  L.push("", "_Preparation guidance only — not a prediction of interview or offer outcomes._");
  if (a.roleSummary) L.push("", "## Role summary", "", clean(a.roleSummary));

  const core = (a.coreSkills || []).map((s) => (typeof s === "string" ? s : s.name)).filter(Boolean);
  if (core.length || (a.technologies || []).length) {
    L.push("", "## What this job requires");
    if (core.length) L.push("", "**Core skills:** " + core.join(", "));
    if ((a.technologies || []).length) L.push("", "**Technologies:** " + (a.technologies || []).join(", "));
    if ((a.experienceRequirements || []).length) {
      L.push("", "**Experience:**", ...(a.experienceRequirements || []).map((e) => "- " + clean(e)));
    }
  }

  if ((a.readiness || []).length) {
    L.push("", "## Your readiness", "", "| Dimension | Status | Role requires | You have | Gap |", "|---|---|---|---|---|");
    (a.readiness || []).forEach((r) =>
      L.push("| " + [r.dimension, String(r.status || "").replace(/_/g, " "), r.roleRequires, r.candidateHas, r.gap].map(clean).join(" | ") + " |"),
    );
  }

  if ((a.potentialGaps || []).length) {
    L.push("", "## Potential gaps");
    (a.potentialGaps || []).forEach((g) => {
      L.push("", "### " + clean(g.requirement));
      if (g.whatIsMissing) L.push("", "**Missing:** " + clean(g.whatIsMissing));
      if (g.whyItMatters) L.push("", "**Why it matters:** " + clean(g.whyItMatters));
      if ((g.whatToStudy || []).length) L.push("", "**Study:** " + (g.whatToStudy || []).map(clean).join(", "));
      if ((g.whatToBuild || []).length) L.push("**Build:** " + (g.whatToBuild || []).map(clean).join(", "));
      if ((g.whatToPractice || []).length) L.push("**Practice:** " + (g.whatToPractice || []).map(clean).join(", "));
      if (g.interviewExpectation) L.push("", "**In the interview:** " + clean(g.interviewExpectation));
    });
  }

  if ((a.preparationPlan || []).length) {
    L.push("", "## Your preparation plan");
    (a.preparationPlan || []).forEach((p) => {
      L.push("", "### Priority " + clean(p.priority) + " — " + clean(p.title));
      if (p.why) L.push("", clean(p.why));
      if (p.resource?.label) L.push("", "- Resource: " + clean(p.resource.label));
    });
  }

  if (a.nextStep) L.push("", "## Next step", "", clean(a.nextStep));
  L.push("", "---", "Generated by OfferReady · https://klnjoy.github.io/offerready/");
  return L.join("\n") + "\n";
}
