/* Interview Practice over the question bank (was content/assets/practice.js).
 * Modes: Practice (answer → reveal → self-rate), Flashcards, Timed Exam, Weak
 * areas. The bank is generated by build_practice_questions.py and served from
 * the MkDocs site. Sessions are saved locally (ip_history_v1). */

import { Fragment, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { QUESTION_BANK_URL, docsUrl } from "../config";
import { getHistory, record, weakTopicScores } from "../lib/progressStore";
import { ExternalLink, Link } from "../lib/router";
import { Card, Muted } from "../components/ui";

interface BankItem {
  q: string;
  a: string;
  topic: string;
  tracks?: string[];
  source?: string;
}

const TRACKS = {
  all: { label: "All topics", desc: "Everything in the bank." },
  data: { label: "Data / Analytics Eng", desc: "SQL, warehouses, pipelines, Python, AWS." },
  ai: { label: "AI / GenAI Engineer", desc: "RAG, agents, LangChain, MCP, Python." },
  fde: { label: "Forward-Deployed", desc: "Python + behavioral core." },
  lead: { label: "Delivery / Lead", desc: "Behavioral & delivery focus." },
} as const;
type Track = keyof typeof TRACKS;

const MODES = {
  practice: { label: "📝 Practice", desc: "Answer, reveal, self-rate 1-5." },
  flashcard: { label: "🃏 Flashcards", desc: "Flip to reveal, then Again/Good/Easy." },
  exam: { label: "⏱️ Timed Exam", desc: "Countdown, answer all, score at the end." },
  weak: { label: "🎯 Weak areas", desc: "Focuses on topics you've scored low. Needs a little history." },
} as const;
type Mode = keyof typeof MODES;
type RunMode = Exclude<Mode, "weak">;

const SOURCE_LINKS: Record<string, string> = {
  SQL_Interview_QA: "SQL Interview Q&A",
  DataEngineering_Interview_QA: "Data Engineering Interview Q&A",
  Snowflake_Interview_QA: "Snowflake Interview Q&A",
  Databricks_Interview_QA: "Databricks Interview Q&A",
  dbt_Interview_QA: "dbt Interview Q&A",
  Python_Interview_QA: "Python Interview Q&A",
  AWS_Interview_QA: "AWS Interview Q&A",
  DevOps_Interview_QA: "DevOps Interview Q&A",
  AI_Engineer_Interview_QA: "AI Engineer Interview Q&A",
  Agents_Interview_QA: "Agents Interview Q&A",
  LangChain_LangGraph_Interview_QA: "LangChain / LangGraph Interview Q&A",
  MCP_Interview_QA: "MCP Interview Q&A",
  GenAI_Interview_QA: "GenAI Interview Q&A",
  Behavioral_STAR_Interview_QA: "Behavioral / STAR Interview Q&A",
};

// AI grading uses the LOCAL agent (agent/serve.py) — localhost only.
const ON_LOCALHOST = /^(localhost|127\.0\.0\.1|\[::1\])$/.test(window.location.hostname);
const AGENT_URL = "http://localhost:8000";
const EXAM_SECONDS_PER_Q = 90;

const shuffle = <T,>(a: T[]): T[] => {
  const b = a.slice();
  for (let i = b.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [b[i], b[j]] = [b[j], b[i]];
  }
  return b;
};

/** Inline `code` and **bold** from the bank's markdown-ish answers. */
function MdInline({ text }: { text: string }) {
  const parts = String(text || "").split(/(`[^`]+`|\*\*[^*]+\*\*)/g);
  return (
    <>
      {parts.map((p, i) =>
        p.startsWith("`") && p.endsWith("`") && p.length > 1 ? <code key={i}>{p.slice(1, -1)}</code>
        : p.startsWith("**") && p.endsWith("**") && p.length > 3 ? <strong key={i}>{p.slice(2, -2)}</strong>
        : <Fragment key={i}>{p}</Fragment>,
      )}
    </>
  );
}

function SourceLink({ item }: { item: BankItem }) {
  if (!item.source || !SOURCE_LINKS[item.source]) return null;
  return (
    <ExternalLink className="source-link" href={docsUrl("Personal-SourceCode/" + item.source + ".html")}>
      {"📖"} Read the full topic: {SOURCE_LINKS[item.source]} {"↗"}
    </ExternalLink>
  );
}

interface Session {
  items: BankItem[];
  i: number;
  ratings: (number | undefined)[];
  answers: string[];
  mode: RunMode;
  track: string;
  topic: string;
  reviewing: boolean;
}

type Phase = { kind: "loading" } | { kind: "error"; msg: string } | { kind: "setup" } | { kind: "run" } | { kind: "summary"; endedEarly: boolean };

export default function PracticePage() {
  const [bank, setBank] = useState<BankItem[]>([]);
  const [phase, setPhase] = useState<Phase>({ kind: "loading" });
  const [session, setSession] = useState<Session | null>(null);

  useEffect(() => {
    let alive = true;
    fetch(QUESTION_BANK_URL)
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((d) => {
        if (!alive) return;
        const qs: BankItem[] = (d && d.questions) || [];
        setBank(qs);
        setPhase(qs.length ? { kind: "setup" } : { kind: "error", msg: "No questions found." });
      })
      .catch(() => alive && setPhase({ kind: "error", msg: "⚠️ Couldn't load the question bank." }));
    return () => { alive = false; };
  }, []);

  const start = (s: Session) => {
    setSession(s);
    setPhase({ kind: "run" });
  };

  return (
    <div className="page">
      {phase.kind === "loading" && <p className="muted"><em>Loading practice questions{"…"}</em></p>}
      {phase.kind === "error" && <Card><p>{phase.msg}</p><Muted small>The bank is published with the study site at {QUESTION_BANK_URL}.</Muted></Card>}
      {phase.kind === "setup" && <Setup bank={bank} onStart={start} />}
      {phase.kind === "run" && session && (
        <Runner session={session} setSession={setSession}
          onDone={(endedEarly) => setPhase({ kind: "summary", endedEarly })}
          onQuit={() => setPhase({ kind: "setup" })} />
      )}
      {phase.kind === "summary" && session && (
        <Summary session={session} endedEarly={phase.endedEarly}
          onRetry={(items) => start({ ...session, items: shuffle(items), i: 0, ratings: [], answers: [], mode: "practice", reviewing: false })}
          onNew={() => setPhase({ kind: "setup" })} />
      )}
    </div>
  );
}

function Setup({ bank, onStart }: { bank: BankItem[]; onStart(s: Session): void }) {
  const [mode, setMode] = useState<Mode>("practice");
  const [track, setTrack] = useState<Track>("all");
  const [topic, setTopic] = useState("All");
  const [count, setCount] = useState(10);
  const [notice, setNotice] = useState("");

  const pool = useMemo(() => (track === "all" ? bank : bank.filter((q) => (q.tracks || []).includes(track))), [bank, track]);
  const topics = useMemo(() => ["All", ...Array.from(new Set(pool.map((q) => q.topic))).sort()], [pool]);
  const scores = weakTopicScores();
  const weakest = Object.keys(scores).sort((a, b) => scores[a] - scores[b]).slice(0, 3);
  const history = getHistory();

  const startSession = () => {
    let p = topic !== "All" ? pool.filter((q) => q.topic === topic) : pool.slice();
    if (mode === "weak" && Object.keys(scores).length) {
      // Topics below 70% first (weakest first), then backfill.
      const weight = (q: BankItem) => (q.topic in scores ? scores[q.topic] : 65);
      const weak = p.filter((q) => weight(q) < 70).sort((a, b) => weight(a) - weight(b));
      const rest = p.filter((q) => weight(q) >= 70);
      p = shuffle(weak).concat(shuffle(rest)).slice(0, count);
    } else {
      if (mode === "weak") setNotice("Weak-areas mode gets smarter after you finish a few sessions. For now, here's a normal mixed set — your ratings will train it.");
      p = shuffle(p).slice(0, count);
    }
    if (!p.length) return;
    onStart({ items: p, i: 0, ratings: [], answers: [], mode: mode === "weak" ? "practice" : mode, track: TRACKS[track].label, topic, reviewing: false });
  };

  return (
    <div className="stack">
      <p><strong>{bank.length}</strong> questions loaded. Choose a mode and track, then start. Scores are saved locally in this browser.</p>
      {weakest.length > 0 && (
        <div className="weak-hint">
          {"🎯"} Your weakest topics so far: <strong>{weakest.map((k) => k + " (" + scores[k] + "%)").join(", ")}</strong>. Try <em>Weak areas</em> mode to drill them.
        </div>
      )}
      {notice && <p className="hint">{notice}</p>}
      <div className="progress-label">Mode</div>
      <div className="option-grid">
        {(Object.keys(MODES) as Mode[]).map((k) => (
          <button key={k} type="button" className={"option" + (k === mode ? " selected" : "")} aria-pressed={k === mode} onClick={() => setMode(k)}>
            <h3>{MODES[k].label}</h3><p>{MODES[k].desc}</p>
          </button>
        ))}
      </div>
      <div className="progress-label">Track</div>
      <div className="option-grid">
        {(Object.keys(TRACKS) as Track[]).map((k) => (
          <button key={k} type="button" className={"option" + (k === track ? " selected" : "")} aria-pressed={k === track} onClick={() => { setTrack(k); setTopic("All"); }}>
            <h3>{TRACKS[k].label}</h3><p>{TRACKS[k].desc}</p>
          </button>
        ))}
      </div>
      <div className="row wrap">
        <label>Topic: <select className="input input-inline" value={topic} onChange={(e) => setTopic(e.target.value)}>{topics.map((t) => <option key={t} value={t}>{t}</option>)}</select></label>
        <label>Count: <select className="input input-inline" value={count} onChange={(e) => setCount(parseInt(e.target.value, 10))}>{[5, 10, 15, 20].map((n) => <option key={n} value={n}>{n} questions</option>)}</select></label>
        <button type="button" className="btn btn-primary" onClick={startSession}>Start session</button>
      </div>
      {history.length > 0 && (
        <div>
          <h2>Your recent sessions</h2>
          <div className="table-wrap">
            <table>
              <thead><tr><th>When</th><th>Mode</th><th>Track</th><th>Topic</th><th>Score</th></tr></thead>
              <tbody>
                {history.slice(0, 8).map((e, i) => (
                  <tr key={i}><td>{e.when}</td><td>{e.mode || "practice"}</td><td>{e.track}</td><td>{e.topic}</td><td>{e.score}%</td></tr>
                ))}
              </tbody>
            </table>
          </div>
          <Muted small>Saved in this browser. Job-based Interview Readiness lives on your <Link to="/dashboard">dashboard</Link>.</Muted>
        </div>
      )}
    </div>
  );
}

function Runner({
  session: s, setSession, onDone, onQuit,
}: { session: Session; setSession(s: Session): void; onDone(endedEarly: boolean): void; onQuit(): void }) {
  const item = s.items[s.i];
  const [remaining, setRemaining] = useState(s.items.length * EXAM_SECONDS_PER_Q);
  const finishedRef = useRef(false);

  // Exam countdown runs across questions until review.
  useEffect(() => {
    if (s.mode !== "exam" || s.reviewing) return;
    const t = setInterval(() => setRemaining((r) => r - 1), 1000);
    return () => clearInterval(t);
  }, [s.mode, s.reviewing]);
  useEffect(() => {
    if (s.mode === "exam" && !s.reviewing && remaining <= 0 && !finishedRef.current) {
      finishedRef.current = true;
      setSession({ ...s, i: 0, reviewing: true });
    }
  }, [remaining]); // eslint-disable-line react-hooks/exhaustive-deps

  const rate = (val: number) => {
    const ratings = s.ratings.slice();
    ratings[s.i] = val;
    if (s.i + 1 >= s.items.length) { setSession({ ...s, ratings }); onDone(false); return; }
    setSession({ ...s, ratings, i: s.i + 1 });
  };

  const endEarly = () => {
    const rated = s.ratings.filter((r) => r != null).length;
    const msg = rated
      ? "End this session now? Your " + rated + " rated " + (rated === 1 ? "answer" : "answers") + " will be saved to your progress."
      : "End this session? You haven't rated anything yet, so nothing will be saved.";
    if (!window.confirm(msg)) return;
    if (rated) onDone(true);
    else onQuit();
  };

  const fmt = (sec: number) => { const v = Math.max(0, sec); return Math.floor(v / 60) + ":" + String(v % 60).padStart(2, "0"); };
  const examWriting = s.mode === "exam" && !s.reviewing;

  return (
    <div className="card">
      <div className="card-top">
        <div className="progress-label">
          Question {s.i + 1} of {s.items.length} {"·"} {s.track}
          {examWriting && <> {"·"} <span>{fmt(remaining)}</span> left</>}
        </div>
        <button type="button" className="btn btn-ghost btn-small" title="Save progress so far and exit this session" onClick={endEarly}>End session</button>
      </div>
      <div className="bar"><div style={{ width: Math.round((s.i / s.items.length) * 100) + "%" }} /></div>
      <span className="topic">{item.topic}</span>
      <div className="question">{item.q}</div>
      {examWriting ? (
        <ExamWrite key={s.i} s={s} setSession={setSession} onFinish={(answers) => { finishedRef.current = true; setSession({ ...s, answers, i: 0, reviewing: true }); }} />
      ) : s.mode === "exam" ? (
        <>
          <div className="progress-label">Your answer</div>
          <div className="model">{s.answers[s.i] ? s.answers[s.i] : <em>(left blank)</em>}</div>
          <ModelAnswer item={item} title="Model answer" />
          <RatingRow onPick={rate} />
        </>
      ) : s.mode === "flashcard" ? (
        <Flashcard key={s.i} item={item} onPick={rate} />
      ) : (
        <PracticeQ key={s.i} item={item} onPick={rate} />
      )}
    </div>
  );
}

function ModelAnswer({ item, title }: { item: BankItem; title: string }) {
  return (
    <div className="model">
      <h4>{title}</h4>
      <MdInline text={item.a} />
      <div><SourceLink item={item} /></div>
    </div>
  );
}

function RatingRow({ onPick }: { onPick(v: number): void }) {
  return (
    <div>
      <div className="progress-label">How did your answer compare? Rate yourself:</div>
      <div className="rate">
        {["1 · Missed it", "2", "3 · Partial", "4", "5 · Nailed it"].map((lab, i) => (
          <button key={lab} type="button" className="star" onClick={() => onPick(i + 1)}>{lab}</button>
        ))}
      </div>
    </div>
  );
}

function PracticeQ({ item, onPick }: { item: BankItem; onPick(v: number): void }) {
  const [answer, setAnswer] = useState("");
  const [revealed, setRevealed] = useState(false);
  const [ai, setAi] = useState<ReactNode>(null);
  const [aiBusy, setAiBusy] = useState(false);

  const gradeWithAI = async () => {
    if (!answer.trim()) { setAi(<div className="hint">Type an answer first, then click AI grade.</div>); return; }
    setAiBusy(true);
    setAi(<em>Asking the local agent{"…"}</em>);
    try {
      const r = await fetch(AGENT_URL + "/grade", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: item.q, answer, model_answer: item.a }),
      });
      if (!r.ok) throw new Error();
      const d = await r.json();
      setAi(<><strong>AI score: {String(d.score)}/5</strong><br /><MdInline text={d.feedback || ""} /></>);
    } catch {
      setAi(<>{"🔌"} AI grading needs the local agent running. Start it with <code>start-chatbot.bat</code>, then reload. Self-rating always works.</>);
    } finally {
      setAiBusy(false);
    }
  };

  return (
    <>
      <textarea className="input textarea" autoFocus aria-label="Your answer" placeholder="Answer here (or say it out loud), then reveal the model answer."
        value={answer} onChange={(e) => setAnswer(e.target.value)} />
      <div className="row">
        <button type="button" className="btn btn-primary" disabled={revealed} onClick={() => setRevealed(true)}>Reveal model answer</button>
        {ON_LOCALHOST && <button type="button" className="btn btn-ghost" disabled={aiBusy} onClick={gradeWithAI}>{"🤖"} AI grade (local)</button>}
      </div>
      {ai && <div className="ai-out">{ai}</div>}
      {revealed && (<><ModelAnswer item={item} title="Model answer" /><RatingRow onPick={onPick} /></>)}
    </>
  );
}

function Flashcard({ item, onPick }: { item: BankItem; onPick(v: number): void }) {
  const [flipped, setFlipped] = useState(false);
  return (
    <>
      <button type="button" className="btn btn-ghost" disabled={flipped} onClick={() => setFlipped(true)}>Flip to reveal answer</button>
      {flipped && (
        <>
          <ModelAnswer item={item} title="Answer" />
          <div className="rate">
            {([["Again", 1], ["Good", 3], ["Easy", 5]] as const).map(([lab, v]) => (
              <button key={lab} type="button" className="star" onClick={() => onPick(v)}>{lab}</button>
            ))}
          </div>
        </>
      )}
    </>
  );
}

function ExamWrite({ s, setSession, onFinish }: { s: Session; setSession(s: Session): void; onFinish(answers: string[]): void }) {
  // Answers live in the session so a timer expiry keeps what was typed.
  const withAnswer = (text: string) => { const answers = s.answers.slice(); answers[s.i] = text; return answers; };
  const last = s.i === s.items.length - 1;
  return (
    <>
      <textarea className="input textarea" autoFocus aria-label="Your answer" placeholder={"Type your answer. No peeking \u2014 you review at the end."}
        value={s.answers[s.i] || ""} onChange={(e) => setSession({ ...s, answers: withAnswer(e.target.value) })} />
      <div className="row">
        <button type="button" className="btn btn-ghost" disabled={s.i === 0} onClick={() => setSession({ ...s, i: s.i - 1 })}>{"\u2039"} Prev</button>
        <button type="button" className="btn btn-primary" onClick={() => (last ? onFinish(s.answers) : setSession({ ...s, i: s.i + 1 }))}>
          {last ? "Finish & review" : "Next \u203a"}
        </button>
      </div>
    </>
  );
}

function Summary({
  session: s, endedEarly, onRetry, onNew,
}: { session: Session; endedEarly: boolean; onRetry(items: BankItem[]): void; onNew(): void }) {
  const rated = s.ratings.filter((r): r is number => r != null);
  const avg = rated.length ? rated.reduce((a, b) => a + b, 0) / rated.length : 0;
  const score = Math.round((avg / 5) * 100);
  const saved = useRef(false);

  useEffect(() => {
    if (saved.current) return;
    saved.current = true;
    const byTopic: Record<string, number[]> = {};
    s.items.forEach((it, i) => { const r = s.ratings[i]; if (r != null) (byTopic[it.topic] = byTopic[it.topic] || []).push(r); });
    const topics: Record<string, number> = {};
    Object.entries(byTopic).forEach(([k, v]) => { topics[k] = Math.round((v.reduce((a, b) => a + b, 0) / v.length / 5) * 100); });
    record({ mode: s.mode, track: s.track, topic: s.topic, score, n: rated.length, partial: endedEarly, topics });
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const weakItems = s.items.filter((_, i) => s.ratings[i] != null && (s.ratings[i] as number) <= 3);
  const msg = score >= 80 ? "Strong — you're interview-ready on this set." : score >= 60 ? "Solid. Review the ones you rated low and go again." : "Good start. Reread the source pages, then retake.";

  return (
    <div className="card summary">
      {endedEarly && <div className="progress-label">Session ended early {"—"} {rated.length} of {s.items.length} questions rated and saved.</div>}
      <div className="big-score">{score}%</div>
      <p>{MODES[s.mode].label} {"·"} {rated.length} questions {"·"} {s.track} {"·"} {s.topic}</p>
      <p>{msg}</p>
      <div className="row wrap">
        {weakItems.length > 0 && <button type="button" className="btn btn-primary" onClick={() => onRetry(weakItems)}>Retry {weakItems.length} I rated low</button>}
        <button type="button" className={"btn" + (weakItems.length ? " btn-ghost" : " btn-primary")} onClick={onNew}>New session</button>
        <Link className="btn btn-ghost" to="/defend">Defend a decision {"→"}</Link>
      </div>
    </div>
  );
}
